### ISSUE TITLE
Getting "crypto" is indefined with IE11

### ISSUE THREAD

**Issue by ThorstenKunz** [bitjourney/uuid-v4-js#1]
When using IE11 the following code line in rng.js is triggering a "crypto is undefined" error:

`return msCrypto.getRandomValues.bind(crypto);`

**Comment by IceBreakerG** [comment]
I ran into this issue as well.  I fixed it by changing that line to:

`return msCrypto.getRandomValues.bind(msCrypto);`

in the rng.js file in `dist`.  I also changed it in rng.ts in `src`.

Edit: I just submitted a pull request to fix this issue.

**Comment by gfx** [comment]
Fixed in https://github.com/bitjourney/uuid-v4-js/pull/2

Thanks.
